import type { Business, LocationCandidate, Sector, SearchStep } from "@geosector/shared";

export const sectors: Sector[] = [
  {
    slug: "hospitality",
    name: "Hosteleria",
    description: "Restaurantes, cafeterias, bares, pubs y consumo presencial.",
    enabled: true,
    defaultCategories: ["restaurant", "cafe", "bar", "pub", "fast_food", "food_court", "ice_cream"],
  },
];

export const cityLocations: LocationCandidate[] = [
  {
    id: "alicante",
    label: "Alicante, Espana",
    type: "city",
    country: "Espana",
    countryCode: "ES",
    region: "Comunitat Valenciana",
    city: "Alicante",
    lat: 38.3452,
    lng: -0.481,
    boundingBox: { south: 38.27, west: -0.59, north: 38.43, east: -0.36 },
  },
  {
    id: "madrid",
    label: "Madrid, Espana",
    type: "city",
    country: "Espana",
    countryCode: "ES",
    region: "Comunidad de Madrid",
    city: "Madrid",
    lat: 40.4168,
    lng: -3.7038,
  },
  {
    id: "lisbon",
    label: "Lisboa, Portugal",
    type: "city",
    country: "Portugal",
    countryCode: "PT",
    city: "Lisboa",
    lat: 38.7223,
    lng: -9.1393,
  },
  {
    id: "paris",
    label: "Paris, Francia",
    type: "city",
    country: "Francia",
    countryCode: "FR",
    city: "Paris",
    lat: 48.8566,
    lng: 2.3522,
  },
  {
    id: "new-york",
    label: "New York, Estados Unidos",
    type: "city",
    country: "Estados Unidos",
    countryCode: "US",
    city: "New York",
    lat: 40.7128,
    lng: -74.006,
  },
  {
    id: "tokyo",
    label: "Tokyo, Japon",
    type: "city",
    country: "Japon",
    countryCode: "JP",
    city: "Tokyo",
    lat: 35.6762,
    lng: 139.6503,
  },
];

export const countryLocations: LocationCandidate[] = [
  {
    id: "spain",
    label: "Espana",
    type: "country",
    country: "Espana",
    countryCode: "ES",
    lat: 40.4637,
    lng: -3.7492,
    boundingBox: { south: 27.43, west: -18.16, north: 43.79, east: 4.32 },
  },
  {
    id: "portugal",
    label: "Portugal",
    type: "country",
    country: "Portugal",
    countryCode: "PT",
    lat: 39.3999,
    lng: -8.2245,
  },
  {
    id: "france",
    label: "Francia",
    type: "country",
    country: "Francia",
    countryCode: "FR",
    lat: 46.2276,
    lng: 2.2137,
  },
  {
    id: "japan",
    label: "Japon",
    type: "country",
    country: "Japon",
    countryCode: "JP",
    lat: 36.2048,
    lng: 138.2529,
  },
];

export const mockBusinesses: Business[] = [
  {
    id: "b-1",
    canonicalName: "Nodo Restaurant",
    sectorSlug: "hospitality",
    primaryCategory: "restaurant",
    rawCategories: ["amenity=restaurant", "cuisine=mediterranean"],
    address: "Centro historico",
    city: "Alicante",
    country: "Espana",
    countryCode: "ES",
    lat: 38.3458,
    lng: -0.4822,
    phone: "+34 965 000 001",
    website: "https://example.com",
    confidenceScore: 0.91,
    sourceName: "OpenStreetMap",
    sourceExternalId: "node/1001",
  },
  {
    id: "b-2",
    canonicalName: "Mercado Cafe",
    sectorSlug: "hospitality",
    primaryCategory: "cafe",
    rawCategories: ["amenity=cafe"],
    address: "Mercado Central",
    city: "Alicante",
    country: "Espana",
    countryCode: "ES",
    lat: 38.3467,
    lng: -0.4863,
    confidenceScore: 0.84,
    sourceName: "OpenStreetMap",
    sourceExternalId: "way/1002",
  },
  {
    id: "b-3",
    canonicalName: "Puerto Bar",
    sectorSlug: "hospitality",
    primaryCategory: "bar",
    rawCategories: ["amenity=bar"],
    address: "Marina",
    city: "Alicante",
    country: "Espana",
    countryCode: "ES",
    lat: 38.3408,
    lng: -0.4772,
    phone: "+34 965 000 003",
    confidenceScore: 0.78,
    sourceName: "OpenStreetMap",
    sourceExternalId: "node/1003",
  },
];

export const operationSteps: Array<{ step: SearchStep; label: string }> = [
  { step: "resolving_location", label: "Resolviendo zona" },
  { step: "querying_osm", label: "Consultando OpenStreetMap" },
  { step: "normalizing_entities", label: "Normalizando entidades" },
  { step: "deduplicating_candidates", label: "Deduplicando candidatos" },
  { step: "saving_results", label: "Guardando resultados" },
  { step: "completed", label: "Finalizado" },
];
